# Generated by Django 2.0.6 on 2018-06-23 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13, unique=True, verbose_name='CEDULA DE IDENTIDAD')),
                ('nombre1', models.CharField(max_length=50, verbose_name='PRIMER NOMBRE')),
                ('nombre2', models.CharField(max_length=50, verbose_name='SEGUNDO NOMBRE')),
                ('apellPadre', models.CharField(max_length=50, verbose_name='PRIMER APELLIDO')),
                ('apellMadre', models.CharField(max_length=50, verbose_name='SEGUNDO APELLIDO')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=2)),
                ('direccion', models.CharField(max_length=100, verbose_name='DIRECCION DOMICILIARIA')),
                ('fechNacimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de naciemiento')),
                ('lugarNacimiento', models.CharField(max_length=100, verbose_name='LUGAR DE NACIMIENTO')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='NACIONALIDAD')),
                ('grupoCultural', models.CharField(max_length=100, verbose_name='GRUPO CULTURAL')),
                ('estadoCivil', models.CharField(choices=[('SOL', 'Soltero'), ('CAS', 'Casado'), ('DIV', 'Divorciado'), ('VIU', 'Viudo'), ('UNL', 'Unión libre')], max_length=3)),
                ('instruccion', models.CharField(max_length=100, verbose_name='INSTRUCION EDUCATIVA')),
                ('fechaAdmision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='FECHA DE ADMISION')),
                ('ocupacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='OCUPACION')),
                ('empresa', models.CharField(max_length=100, verbose_name='EMPRESA')),
            ],
        ),
    ]
