# Generated by Django 2.0.6 on 2018-07-06 00:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analisisMamas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tegGlandularizq', models.CharField(choices=[('HOMOGENEO', 'Homogéneo'), ('HETEROGENEO', 'Heterogéneo')], max_length=3)),
                ('infotegGlandularizq', models.CharField(max_length=100)),
                ('tegGlandularder', models.CharField(choices=[('HOMOGENEO', 'Homogéneo'), ('HETEROGENEO', 'Heterogéneo')], max_length=3)),
                ('infotegGlandularder', models.CharField(max_length=100)),
                ('bordesizq', models.CharField(choices=[('REGULAR', 'Regulares'), ('IRREGULAR', 'Irregulares')], max_length=3)),
                ('bordesder', models.CharField(choices=[('REGULAR', 'Regulares'), ('IRREGULAR', 'Irregulares')], max_length=3)),
                ('ecogenidadizq', models.CharField(choices=[('NORMAL', 'Normal'), ('DISMINUIDA', 'Disminuida'), ('AUMENTADA', 'Aumentada')], max_length=3)),
                ('ecogenidadder', models.CharField(choices=[('NORMAL', 'Normal'), ('DISMINUIDA', 'Disminuida'), ('AUMENTADA', 'Aumentada')], max_length=3)),
                ('tejGrasoizq', models.CharField(choices=[('BUENA', 'Buena Cantidad'), ('POCA', 'Poca Cantidad')], max_length=3)),
                ('tejGrasoder', models.CharField(choices=[('BUENA', 'Buena Cantidad'), ('POCA', 'Poca Cantidad')], max_length=3)),
                ('imgExpansivasizq', models.CharField(choices=[('NO', 'No'), ('QUISTICA', 'Quísticas'), ('SOLIDA', 'Sólidas')], max_length=3)),
                ('imgExpansivasder', models.CharField(choices=[('NO', 'No'), ('QUISTICA', 'Quísticas'), ('SOLIDA', 'Sólidas')], max_length=3)),
                ('horarioizq', models.CharField(max_length=400, verbose_name='HORARIO')),
                ('horarioder', models.CharField(max_length=400, verbose_name='HORARIO')),
                ('descripcionizq', models.CharField(max_length=500, verbose_name='DESCRIPCION')),
                ('descripcionder', models.CharField(max_length=500, verbose_name='DESCRIPCION')),
                ('observaciones', models.CharField(max_length=500, verbose_name='OBSERBACIONES')),
                ('presuncion', models.CharField(max_length=800, verbose_name='PRESIÓN DIAGNÓSTICA')),
                ('fech_analisismamas', models.DateTimeField(auto_now_add=True, verbose_name='FECHA DE ADMISION')),
                ('fech_actualizado', models.DateTimeField(auto_now=True, verbose_name='FECHA DE ACTUALIZACION')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precion_arterial', models.CharField(max_length=30, verbose_name='PRESION ARTERIAL')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TEMPERATURA(°C)')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PASO(KG)')),
                ('evolucion', models.CharField(max_length=300, verbose_name='EVOLUCION')),
                ('pulso', models.CharField(max_length=20, verbose_name='PULSO')),
                ('saturacion_oxigeno', models.CharField(max_length=20, verbose_name='SATURACION DE OXIGENO')),
                ('talla', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ESTATURA')),
                ('idx', models.CharField(max_length=100, verbose_name='IDX')),
                ('exmenes', models.CharField(max_length=200, verbose_name='EXAMENES')),
                ('motivo', models.CharField(max_length=300, verbose_name='MOTIVO')),
                ('fechaDiagnostico', models.DateTimeField(auto_now_add=True, verbose_name='FECHA DE DIAGNOSTICO')),
                ('fech_actualizado', models.DateTimeField(auto_now=True, verbose_name='FECHA DE ACTUALIZACION')),
            ],
        ),
        migrations.CreateModel(
            name='farmacoterapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmaco', models.CharField(max_length=300, verbose_name='FARMACO')),
                ('adminitracion', models.CharField(max_length=300, verbose_name='ADMINITRACION')),
                ('comentario', models.CharField(max_length=300, verbose_name='ADMINITRACION')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Diagnostico', verbose_name='DIAGNOSTICO')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13, unique=True, verbose_name='CEDULA DE IDENTIDAD')),
                ('nombre1', models.CharField(max_length=50, verbose_name='PRIMER NOMBRE')),
                ('nombre2', models.CharField(max_length=50, verbose_name='SEGUNDO NOMBRE')),
                ('apellPadre', models.CharField(max_length=50, verbose_name='PRIMER APELLIDO')),
                ('apellMadre', models.CharField(max_length=50, verbose_name='SEGUNDO APELLIDO')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=2)),
                ('direccion', models.CharField(max_length=100, verbose_name='DIRECCION DOMICILIARIA')),
                ('fechNacimiento', models.DateField(default=django.utils.timezone.now, verbose_name='fecha de naciemiento')),
                ('lugarNacimiento', models.CharField(max_length=100, verbose_name='LUGAR DE NACIMIENTO')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='NACIONALIDAD')),
                ('grupoCultural', models.CharField(max_length=100, verbose_name='GRUPO CULTURAL')),
                ('estadoCivil', models.CharField(choices=[('SOL', 'Soltero'), ('CAS', 'Casado'), ('DIV', 'Divorciado'), ('VIU', 'Viudo'), ('UNL', 'Unión libre')], max_length=3)),
                ('instruccion', models.CharField(max_length=100, verbose_name='INSTRUCION EDUCATIVA')),
                ('ocupacion', models.CharField(max_length=100, verbose_name='OCUPACION')),
                ('empresa', models.CharField(max_length=100, verbose_name='EMPRESA')),
                ('tipo_sangre', models.CharField(max_length=100, verbose_name='TIPO DE SANGRE')),
                ('tipo_seguro', models.CharField(max_length=100, verbose_name='TIPO DE SEGURIDAD')),
                ('telefono', models.CharField(max_length=9, verbose_name='TELEFONO DEL PACIENTE')),
                ('celular', models.CharField(max_length=10, verbose_name='CELULAR DEL PACIENT')),
                ('correo', models.EmailField(max_length=254, verbose_name='CORREO DEL PACIENT')),
                ('pariente', models.CharField(max_length=100, verbose_name='NOMBRE PARIENTE')),
                ('parentesco', models.CharField(max_length=100, verbose_name='PARENTESCO')),
                ('telefono_pariente', models.CharField(max_length=9, verbose_name='TELEFONO DEL REFERIDO')),
                ('celular_pariente', models.CharField(max_length=10, verbose_name='CELULAR DEL REFERIDO')),
                ('foto', models.ImageField(upload_to='fotos')),
                ('fech_creado', models.DateTimeField(auto_now_add=True, verbose_name='FECHA DE ADMISION')),
                ('fech_actualizado', models.DateTimeField(auto_now=True, verbose_name='FECHA DE ACTUALIZACION')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Paciente', verbose_name='PACIENTE'),
        ),
        migrations.AddField(
            model_name='analisismamas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Paciente', verbose_name='PACIENTE'),
        ),
    ]
