# Generated by Django 2.0.6 on 2018-07-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisismamas',
            name='bordesder',
            field=models.CharField(choices=[('REGULAR', 'Regulares'), ('IRREGULAR', 'Irregulares')], max_length=20),
        ),
        migrations.AlterField(
            model_name='analisismamas',
            name='bordesizq',
            field=models.CharField(choices=[('REGULAR', 'Regulares'), ('IRREGULAR', 'Irregulares')], max_length=20),
        ),
        migrations.AlterField(
            model_name='analisismamas',
            name='ecogenidadder',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('DISMINUIDA', 'Disminuida'), ('AUMENTADA', 'Aumentada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='analisismamas',
            name='ecogenidadizq',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('DISMINUIDA', 'Disminuida'), ('AUMENTADA', 'Aumentada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='analisismamas',
            name='imgExpansivasder',
            field=models.CharField(choices=[('NO', 'No'), ('QUISTICA', 'Quísticas'), ('SOLIDA', 'Sólidas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='analisismamas',
            name='imgExpansivasizq',
            field=models.CharField(choices=[('NO', 'No'), ('QUISTICA', 'Quísticas'), ('SOLIDA', 'Sólidas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='analisismamas',
            name='tegGlandularder',
            field=models.CharField(choices=[('HOMOGENEO', 'Homogéneo'), ('HETEROGENEO', 'Heterogéneo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='analisismamas',
            name='tegGlandularizq',
            field=models.CharField(choices=[('HOMOGENEO', 'Homogéneo'), ('HETEROGENEO', 'Heterogéneo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='analisismamas',
            name='tejGrasoder',
            field=models.CharField(choices=[('BUENA', 'Buena Cantidad'), ('POCA', 'Poca Cantidad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='analisismamas',
            name='tejGrasoizq',
            field=models.CharField(choices=[('BUENA', 'Buena Cantidad'), ('POCA', 'Poca Cantidad')], max_length=20),
        ),
    ]
