# Generated by Django 2.0.6 on 2018-06-25 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precion_arterial', models.CharField(max_length=30, verbose_name='PRESION ARTERIAL')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evolucion', models.CharField(max_length=300, verbose_name='CELULAR DEL REFERIDO')),
                ('pulso', models.CharField(max_length=20, verbose_name='CELULAR DEL REFERIDO')),
                ('saturacion_oxigeno', models.CharField(max_length=20, verbose_name='SATURACION DE OXIGENO')),
                ('talla', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idx', models.CharField(max_length=100, verbose_name='IDX')),
                ('exmenes', models.CharField(max_length=200, verbose_name='EXAMENES')),
                ('motivo', models.CharField(max_length=300, verbose_name='MOTIVO')),
                ('fechaDiagnostico', models.DateTimeField(auto_now_add=True, verbose_name='FECHA DE DIAGNOSTICO')),
                ('fech_actualizado', models.DateTimeField(auto_now=True, verbose_name='FECHA DE ACTUALIZACION')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Paciente')),
            ],
        ),
    ]
