# Generated by Django 2.0.6 on 2018-07-18 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0002_ecografiaginecologico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecografiatesticular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivoExamen', models.CharField(max_length=500, verbose_name='MOTIVO DEL EXAMEN')),
                ('testiculoder', models.CharField(max_length=300, verbose_name='DERECHO')),
                ('epididimoder', models.CharField(max_length=300, verbose_name='EPIDIDIMODER')),
                ('liqescrotalder', models.CharField(max_length=300, verbose_name='LIQUIDO INTRA ESCROTAL')),
                ('testiculoizq', models.CharField(max_length=300, verbose_name='IZQUIERDO')),
                ('epididimoizq', models.CharField(max_length=300, verbose_name='EPIDIDIMODER')),
                ('liqescrotalizq', models.CharField(max_length=300, verbose_name='LIQUIDO INTRA ESCROTAL')),
                ('observacion', models.CharField(max_length=500, verbose_name='OBSERVACION')),
                ('presuncionDiagnostico', models.CharField(max_length=500, verbose_name='PRESUNCION_DIAGNOSTICA')),
                ('fech_informe', models.DateTimeField(auto_now_add=True, verbose_name='FECHA INFORME ECOGRAFICO TESTICULAR')),
                ('fech_actualizado', models.DateTimeField(auto_now=True, verbose_name='FECHA DE ACTUALIZACION')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Paciente', verbose_name='PACIENTE')),
            ],
        ),
    ]
