# Generated by Django 2.0.6 on 2018-07-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0002_auto_20180706_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='analisisAbdominal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movilidad_higado', models.CharField(choices=[('NORMAL', 'Normal'), ('ANORMAL', 'Anormal')], max_length=20)),
                ('bordes_higado', models.CharField(choices=[('REGULAR', 'Regulares'), ('IRREGULAR', 'Irregulares')], max_length=20)),
                ('dimension_higado', models.CharField(choices=[('NORMALES', 'Normales'), ('OTROS', 'Otros')], max_length=20)),
                ('parenquima_higado', models.CharField(choices=[('HOMOGENEO', 'Homogéneo'), ('HETEROGENEO', 'Heterogéneo')], max_length=20)),
                ('ecogenicidad_higado', models.CharField(choices=[('NORMAL', 'Normal'), ('DISMINUIDA', 'Disminuida'), ('AUMENTADA', 'Aumentada')], max_length=20)),
                ('imgExpansivas_higado', models.CharField(choices=[('NO', 'No'), ('SI', 'Si')], max_length=2)),
                ('dilatacionVilar_higado', models.CharField(choices=[('NO', 'No'), ('SI', 'Si')], max_length=2)),
                ('coledoco_higado', models.CharField(max_length=200, verbose_name='COLEDOCO')),
                ('forma_vesicula', models.CharField(max_length=200, verbose_name='FORMA')),
                ('paredes_vesicula', models.CharField(choices=[('REGULAR', 'Regulares'), ('IRREGULAR', 'Irregulares')], max_length=20)),
                ('contenidoanecoico_vesicula', models.CharField(choices=[('NO', 'No'), ('SI', 'Si')], max_length=2)),
                ('calculointerno_vesicula', models.CharField(max_length=200, verbose_name='CALCULOS INTERNOS')),
                ('diametrotransverso_vesicula', models.CharField(max_length=200, verbose_name='DIAMETRO TRANSVERSOS')),
                ('ecogenicidad_pancreas', models.CharField(choices=[('NORMAL', 'Normal'), ('ANORMAL', 'Anormal')], max_length=20)),
                ('medidas_pancreas', models.CharField(max_length=200, verbose_name='MEDIDAS')),
                ('ecogenidad_bazo', models.CharField(choices=[('NORMAL', 'Normal'), ('ANORMAL', 'Anormal')], max_length=20)),
                ('medidas_bazo', models.CharField(max_length=200, verbose_name='MEDIDAS')),
                ('aorta', models.CharField(max_length=200, verbose_name='CALIBRES')),
                ('liquido_abdominal', models.CharField(choices=[('NO', 'No'), ('SI', 'Si')], max_length=2)),
                ('observaciones', models.CharField(max_length=200, verbose_name='OBSERBACIONES')),
                ('presuncion_diagnostico', models.CharField(max_length=500, verbose_name='PRESUNCION_DIAGNOSTICA')),
                ('fech_analisisabdomen', models.DateTimeField(auto_now_add=True, verbose_name='FECHA DE ADMISION')),
                ('fech_actualizado', models.DateTimeField(auto_now=True, verbose_name='FECHA DE ACTUALIZACION')),
            ],
        ),
    ]
