# Generated by Django 2.0.6 on 2018-07-05 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0002_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='evolucion',
            field=models.CharField(max_length=300, verbose_name='EVOLUCION'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Paciente', verbose_name='PACIENTE'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PASO(KG)'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='pulso',
            field=models.CharField(max_length=20, verbose_name='PULSO'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='talla',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ESTATURA'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TEMPERATURA(°C)'),
        ),
    ]
