# Generated by Django 2.0.6 on 2018-07-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0003_analisisabdominal'),
    ]

    operations = [
        migrations.CreateModel(
            name='analisisObstetrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=1)),
                ('situacion', models.CharField(choices=[('LONGITUDINAL', 'Longitudinal'), ('TRANSVERSAL', 'TRANSVERSAL'), ('OBLICUA', 'Oblicua')], max_length=20)),
                ('presentacion', models.CharField(choices=[('CEFALICO', 'Cefalico'), ('PODALICO', 'Podalico'), ('OTROS', 'Otros')], max_length=20)),
                ('dorso', models.CharField(choices=[('IZQUIERDA', 'Izquierda'), ('DERECHA', 'Derecha'), ('ANTERIOR', 'Anterior'), ('POSTERIOR', 'Posterior')], max_length=20)),
                ('dbp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='DBP(mm)')),
                ('lf', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='LF(mm)')),
                ('sg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='SG(mm)')),
                ('lcn', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='LCN(mm)')),
                ('columnaVertebral', models.CharField(choices=[('PRESENTE', 'Presente'), ('CAMARA GASTRICA', 'Camara Gástrica')], max_length=20)),
                ('riñon', models.CharField(choices=[('PRESENTE', 'Presente'), ('VEJIGA', 'Vejiga')], max_length=20)),
                ('actividadCardiaca', models.CharField(choices=[('PRESENTE', 'Presente'), ('OTRO', 'Otro')], max_length=20)),
                ('movimientoFetal', models.CharField(choices=[('PRESENTE', 'Presente'), ('OTRO', 'Otro')], max_length=20)),
                ('descrionFetal', models.CharField(max_length=300, verbose_name='DESCRIPCION')),
                ('localizacionPlacenta', models.CharField(choices=[('FUNDICA', 'Fúndica'), ('ANTERIOR', 'Anterior'), ('POSTERIOR', 'Posterior'), ('OTROS', 'Otras Posiciones')], max_length=20)),
                ('grado', models.CharField(choices=[('0', '0'), ('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=20)),
                ('espesorplacenta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Espesor placentario(mm)')),
                ('descrionplacenta', models.CharField(max_length=300, verbose_name='DESCRIPCION')),
                ('volumen', models.CharField(choices=[('NORMAL', 'Fúndica'), ('OLIGOHIDRAMNIOS', 'Oligohidramnios'), ('POLIHIDRAMNIOS', 'Polihidramnios')], max_length=20)),
                ('descrionamniotica', models.CharField(max_length=300, verbose_name='DESCRIPCION')),
                ('circulardecordon', models.CharField(choices=[('NO', 'No'), ('SI', 'Si')], max_length=2)),
                ('observaciones', models.CharField(max_length=300, verbose_name='OBSERVACIONES')),
                ('presuncionDiagnostico', models.CharField(max_length=500, verbose_name='PRESUNCION_DIAGNOSTICA:El estudio Ultrasonografico es compatible con:')),
            ],
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PESO(KG)'),
        ),
    ]
