# Generated by Django 2.0.6 on 2018-07-19 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0003_ecografiatesticular'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecografiaprostata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repelecion', models.CharField(choices=[('BUENA', 'Buena'), ('VACUA', 'Vacua'), ('POCA', 'Poca')], max_length=20)),
                ('paredes', models.CharField(choices=[('REGULARES', 'Regulares'), ('IRREGULARES', 'Irregulares'), ('DELGADA', 'Delgada'), ('ENGROSADA', 'Engrosada')], max_length=20)),
                ('contenidoanecoico', models.CharField(max_length=50, verbose_name='Contenido Anecoico')),
                ('imgExpansivas', models.CharField(max_length=50, verbose_name='Imagenes expansivas')),
                ('calculointerior', models.CharField(max_length=50, verbose_name='Cálculo en su interior')),
                ('volpremiccional', models.CharField(max_length=200, verbose_name='Vol. Pre-miccional')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion/Otros')),
                ('bordes', models.CharField(max_length=100, verbose_name='Bordes')),
                ('dimensiones', models.CharField(max_length=400, verbose_name='Dimensiones')),
                ('volumen', models.CharField(max_length=100, verbose_name='Volumen')),
                ('ecoestructura', models.CharField(max_length=100, verbose_name='Bordes')),
                ('observacion', models.CharField(max_length=500, verbose_name='OBSERVACION')),
                ('presuncionDiagnostico', models.CharField(max_length=500, verbose_name='PRESUNCION_DIAGNOSTICA')),
                ('fech_informe', models.DateTimeField(auto_now_add=True, verbose_name='FECHA INFORME ECOGRAFICO PROSTATA')),
                ('fech_actualizado', models.DateTimeField(auto_now=True, verbose_name='FECHA DE ACTUALIZACION')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Paciente', verbose_name='PACIENTE')),
            ],
        ),
    ]
