# Generated by Django 2.0.6 on 2018-07-06 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0003_auto_20180705_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmacoterapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmaco', models.CharField(max_length=300, verbose_name='FARMACO')),
                ('adminitracion', models.CharField(max_length=300, verbose_name='ADMINITRACION')),
                ('comentario', models.CharField(max_length=300, verbose_name='ADMINITRACION')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Diagnostico', verbose_name='DIAGNOSTICO')),
            ],
        ),
    ]
