# Generated by Django 2.0.6 on 2019-02-08 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0004_ecografiaprostata'),
    ]

    operations = [
        migrations.CreateModel(
            name='desintometria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.CharField(max_length=50, verbose_name='Encabezado')),
                ('observaciones', models.CharField(max_length=10000, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='ekg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.CharField(max_length=50, verbose_name='Encabezado')),
                ('observaciones', models.CharField(max_length=10000, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='rayosx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.CharField(max_length=50, verbose_name='Encabezado')),
                ('observaciones', models.CharField(max_length=10000, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='terapias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.CharField(max_length=50, verbose_name='Encabezado')),
                ('observaciones', models.CharField(max_length=10000, verbose_name='Observaciones')),
            ],
        ),
        migrations.AlterField(
            model_name='farmacoterapia',
            name='adminitracion',
            field=models.CharField(max_length=300, verbose_name='Administracion'),
        ),
        migrations.AlterField(
            model_name='farmacoterapia',
            name='comentario',
            field=models.CharField(max_length=300, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='farmacoterapia',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Diagnostico', verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='farmacoterapia',
            name='farmaco',
            field=models.CharField(max_length=300, verbose_name='Farmaco'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellMadre',
            field=models.CharField(max_length=50, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellPadre',
            field=models.CharField(max_length=50, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=13, unique=True, verbose_name='Cedula de indentidad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(max_length=10, verbose_name='Celular del paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular_pariente',
            field=models.CharField(max_length=10, verbose_name='Celular del referido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo del paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fech_creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de admision'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre1',
            field=models.CharField(max_length=50, verbose_name='Primer nombre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre2',
            field=models.CharField(max_length=50, verbose_name='Segundo nombre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='parentesco',
            field=models.CharField(max_length=100, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=9, verbose_name='Telefono del paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_pariente',
            field=models.CharField(max_length=9, verbose_name='Telefono del pariente'),
        ),
        migrations.AddField(
            model_name='terapias',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Paciente', verbose_name='PACIENTE'),
        ),
        migrations.AddField(
            model_name='rayosx',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Paciente', verbose_name='PACIENTE'),
        ),
        migrations.AddField(
            model_name='ekg',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Paciente', verbose_name='PACIENTE'),
        ),
        migrations.AddField(
            model_name='desintometria',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.Paciente', verbose_name='PACIENTE'),
        ),
    ]
