# Generated by Django 2.0.6 on 2019-02-09 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0005_auto_20190208_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='desintometria',
            name='fech_actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='desintometria',
            name='fech_informe',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ekg',
            name='fech_actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='ekg',
            name='fech_informe',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rayosx',
            name='fech_actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='rayosx',
            name='fech_informe',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terapias',
            name='fech_actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='terapias',
            name='fech_informe',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=''),
            preserve_default=False,
        ),
    ]
