# Generated by Django 2.0.6 on 2019-02-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0007_auto_20190208_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desintometria',
            name='fech_actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='desintometria',
            name='fech_informe',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ekg',
            name='fech_actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ekg',
            name='fech_informe',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='rayosx',
            name='fech_actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='rayosx',
            name='fech_informe',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='terapias',
            name='fech_actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='terapias',
            name='fech_informe',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
    ]
