# Generated by Django 2.0.6 on 2019-03-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0008_auto_20190208_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisabdominal',
            name='encargado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENCARGADO'),
        ),
        migrations.AddField(
            model_name='analisismamas',
            name='encargado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENCARGADO'),
        ),
        migrations.AddField(
            model_name='analisisobstetrico',
            name='encargado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENCARGADO'),
        ),
        migrations.AddField(
            model_name='desintometria',
            name='encargado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENCARGADO'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='encargado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENCARGADO'),
        ),
        migrations.AddField(
            model_name='ecografiaginecologico',
            name='encargado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENCARGADO'),
        ),
        migrations.AddField(
            model_name='ecografiaprostata',
            name='encargado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENCARGADO'),
        ),
        migrations.AddField(
            model_name='ecografiarenal',
            name='encargado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENCARGADO'),
        ),
        migrations.AddField(
            model_name='ecografiatesticular',
            name='encargado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENCARGADO'),
        ),
        migrations.AddField(
            model_name='ekg',
            name='encargado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENCARGADO'),
        ),
        migrations.AddField(
            model_name='rayosx',
            name='encargado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENCARGADO'),
        ),
        migrations.AddField(
            model_name='terapias',
            name='encargado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENCARGADO'),
        ),
    ]
