# Generated by Django 2.0.6 on 2019-03-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0010_auto_20190327_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='acurico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='acurico'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='agcarcinoembrionario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='agcarcinoembrionario'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='agprostespcif',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='agprostespcif'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='agprostespecificolibre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='agprostespecificolibre'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='albumina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='albumina'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='alfafetoproteina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='alfafetoproteina'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='amilasaorina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='amilasaorina'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='amilasaserica',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='amilasaserica'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='asto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='asto'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='bdirecta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bdirecta'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='betaestradiol',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='betaestradiol'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='bilirrubinatotal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bilirrubinatotal'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='bindirecta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bindirecta'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='ca125ovario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ca125ovario'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='ca153mama',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ca153mama'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='ca199pancreas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ca199pancreas'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='ca724gastrico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ca724gastrico'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='calcio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='calcio'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='chiamydia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='chiamydia'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='cloro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cloro'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='colesterol',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='colesterol'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='colinesterasa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='colinesterasa'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='contajedecolonias',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='contajedecolonias'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='cpk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cpk'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='cpkmb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cpkmb'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='creatinina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='creatinina'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='cultivoyambiograma',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cultivoyambiograma'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='cultivoyantibiograma',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cultivoyantibiograma'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='cultivoyantibiogramastrpa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cultivoyantibiogramastrpa'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='cultivoyantibiogramavaginal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cultivoyantibiogramavaginal'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='dengue',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dengue'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='depuraciondecreatinina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='depuraciondecreatinina'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='dlh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dlh'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='enfresco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='enfresco'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='eritrosidimentacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='eritrosidimentacion'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='estuddemocofecal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='estuddemocofecal'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='factorrematoideo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='factorrematoideo'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='factorrh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='factorrh'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='feserico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='feserico'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='fibrinogeno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fibrinogeno'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='fisico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fisico'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='fofatacidaprost',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fofatacidaprost'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='fofatalcalina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fofatalcalina'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='fsh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fsh'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='ggtp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ggtp'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='globulina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='globulina'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='glucosa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='glucosa'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='glucosapostprandial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='glucosapostprandial'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='got',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='got'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='gpt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='gpt'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='gravindex',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='gravindex'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='gruposanguineo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='gruposanguineo'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='hcgsubbetacuantit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hcgsubbetacuantit'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='hcgsubbetaembarazo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hcgsubbetaembarazo'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='hdeshiling',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='H. de Shiling'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='hdlcoleseterol',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hdlcoleseterol'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='hematies',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hematies'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='hematocrito',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hematocrito'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='hemoglobina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hemoglobina'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='hemoglobinaglicosilada',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hemoglobinaglicosilada'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='hepatitisalgg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hepatitisalgg'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='hepatitisalgm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hepatitisalgm'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='hepatitisbhbsag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hepatitisbhbsag'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='hepatitisc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hepatitisc'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='ige',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ige'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='indicterico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='indicterico'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='ldlcolesterol',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ldlcolesterol'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='leucocitos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='leucocitos'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='lipasaserica',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='lipasaserica'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='lipidostotales',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='lipidostotales'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='magnesio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='magnesio'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='neisseria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='neisseria'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='otros',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='otros'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='parasitologico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='parasitologico'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='parasitos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='parasitos'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='plaquetas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='plaquetas'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='plasmodium',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='plasmodium'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='porcentdeesosinofilos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='porcentdeesosinofilos'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='porconcentracion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='porconcentracion'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='potasio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='potasio'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='progesterona',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='progesterona'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='prolactina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='prolactina'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='proteinasenorina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='proteinasenorina'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='proteinastotales',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='proteinastotales'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='quimico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='quimico'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='ratest',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ratest'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='rcreactiva',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='rcreactiva'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='rdewidal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='rdewidal'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='reticulocitos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='reticulocitos'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='rotavirus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='rotavirus'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='sangreoculta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sangreoculta'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='sedimiento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sedimiento'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='sodio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sodio'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='t3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='t3'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='t4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='t4'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='tdecoagulacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tdecoagulacion'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='tdeprotombina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tdeprotombina'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='tdesangria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tdesangria'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='tdetromboplast',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tdetromboplast'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='testdecombs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='testdecombs'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='testosterona',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='testosterona'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='testtoleranciaglucosa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='testtoleranciaglucosa'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='tinciondegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tinciondegram'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='toxoplasmalgg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='toxoplasmalgg'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='toxoplasmalgm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='toxoplasmalgm'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='trigliceridos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='trigliceridos'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='trinciondegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='trinciondegram'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='tsh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tsh'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='urea',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='urea'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='vdrlcualit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='vdrlcualit'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='vdrlcuantit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='vdrlcuantit'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='vih',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='vih'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='vurusherpes1lgg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='vurusherpes1lgg'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='vurusherpes1y2lgm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='vurusherpes1y2lgm'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='vurusherpes2lgg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='vurusherpes2lgg'),
        ),
        migrations.AlterField(
            model_name='lab_analisisclinico',
            name='zielbdek',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='zielbdek'),
        ),
    ]
