from django.db import models
from django.utils import timezone
from datetime import datetime,timedelta
from django.utils.timezone import now
from django.urls import reverse
# Create your models here.

class Paciente(models.Model):
	cedula=models.CharField(max_length=13,unique=True,verbose_name='Cedula de indentidad')
	nombre1=models.CharField(max_length=50,verbose_name='Primer nombre')
	nombre2=models.CharField(max_length=50,verbose_name='Segundo nombre')
	apellPadre=models.CharField(max_length=50,verbose_name='Apellido paterno')
	apellMadre=models.CharField(max_length=50,verbose_name='Apellido materno')
	sexo=models.CharField(max_length=2,choices=(('F', 'Femenino'),('M', 'Masculino'),))
	direccion=models.CharField(max_length=100,verbose_name='DIRECCION DOMICILIARIA')
	fechNacimiento=models.DateField('fecha de naciemiento',default=timezone.now)
	lugarNacimiento=models.CharField(max_length=100,verbose_name='LUGAR DE NACIMIENTO')
	nacionalidad=models.CharField(max_length=100,verbose_name='NACIONALIDAD')
	grupoCultural=models.CharField(max_length=100,verbose_name='GRUPO CULTURAL')
	estadoCivil=models.CharField(max_length=3,choices=(('SOL', 'Soltero'),('CAS', 'Casado'),('DIV', 'Divorciado'),('VIU', 'Viudo'),('UNL', 'Unión libre')))
	instruccion=models.CharField(max_length=100,verbose_name='INSTRUCION EDUCATIVA')
	ocupacion=models.CharField(max_length=100,verbose_name='OCUPACION')
	empresa=models.CharField(max_length=100,verbose_name='EMPRESA')
	tipo_sangre=models.CharField(max_length=100,verbose_name='TIPO DE SANGRE')
	tipo_seguro=models.CharField(max_length=100,verbose_name='TIPO DE SEGURIDAD')
	telefono=models.CharField(max_length=9,verbose_name='Telefono del paciente')
	celular=models.CharField(max_length=10,verbose_name='Celular del paciente')
	correo=models.EmailField(verbose_name='Correo del paciente')
	pariente=models.CharField(max_length=100,verbose_name='NOMBRE PARIENTE')
	parentesco=models.CharField(max_length=100,verbose_name='Parentesco')
	telefono_pariente=models.CharField(max_length=9,verbose_name='Telefono del pariente')
	celular_pariente=models.CharField(max_length=10,verbose_name='Celular del referido')
	foto=models.ImageField(upload_to='fotos', null=True,blank=True)
	fech_creado=models.DateTimeField(auto_now_add=True,verbose_name='Fecha de admision')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='FECHA DE ACTUALIZACION')

	def get_absolute_url(self):
		return reverse('registros:detail',kwargs={'pk':self.pk})

	def __str__(self):
		return self.apellPadre+' '+self.apellMadre+' '+self.nombre1+' '+self.nombre2

class Diagnostico(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	precion_arterial=models.CharField(max_length=30,verbose_name='PRESION ARTERIAL')
	temperatura=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='TEMPERATURA(°C)')
	peso=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='PESO(KG)')
	evolucion=models.CharField(max_length=300,verbose_name='EVOLUCION')
	pulso=models.CharField(max_length=20,verbose_name='PULSO')
	saturacion_oxigeno=models.CharField(max_length=20,verbose_name='SATURACION DE OXIGENO')
	talla=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='ESTATURA')
	idx=models.CharField(max_length=100,verbose_name='IDX')
	exmenes=models.CharField(max_length=200,verbose_name='EXAMENES')
	motivo=models.CharField(max_length=300,verbose_name='MOTIVO')
	fechaDiagnostico=models.DateTimeField(auto_now_add=True,verbose_name='FECHA DE DIAGNOSTICO')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='FECHA DE ACTUALIZACION')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)

class farmacoterapia(models.Model):
	diagnostico= models.ForeignKey(Diagnostico, on_delete=models.CASCADE,verbose_name='Diagnostico')
	farmaco=models.CharField(max_length=300,verbose_name='Farmaco')
	adminitracion=models.CharField(max_length=300,verbose_name='Administracion')
	comentario=models.CharField(max_length=300,verbose_name='Comentario')

class analisisMamas(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	tegGlandularizq=models.CharField(max_length=20,choices=(('HOMOGENEO', 'Homogéneo'),('HETEROGENEO', 'Heterogéneo')))
	infotegGlandularizq=models.CharField(max_length=100)
	tegGlandularder=models.CharField(max_length=20,choices=(('HOMOGENEO', 'Homogéneo'),('HETEROGENEO', 'Heterogéneo')))
	infotegGlandularder=models.CharField(max_length=100)
	bordesizq=models.CharField(max_length=20,choices=(('REGULAR', 'Regulares'),('IRREGULAR', 'Irregulares')))
	bordesder=models.CharField(max_length=20,choices=(('REGULAR', 'Regulares'),('IRREGULAR', 'Irregulares')))
	ecogenidadizq=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('DISMINUIDA', 'Disminuida'),('AUMENTADA', 'Aumentada')))
	ecogenidadder=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('DISMINUIDA', 'Disminuida'),('AUMENTADA', 'Aumentada')))
	tejGrasoizq=models.CharField(max_length=20,choices=(('BUENA', 'Buena Cantidad'),('POCA', 'Poca Cantidad')))
	tejGrasoder=models.CharField(max_length=20,choices=(('BUENA', 'Buena Cantidad'),('POCA', 'Poca Cantidad')))
	imgExpansivasizq=models.CharField(max_length=20,choices=(('NO', 'No'),('QUISTICA', 'Quísticas'),('SOLIDA', 'Sólidas')))
	imgExpansivasder=models.CharField(max_length=20,choices=(('NO', 'No'),('QUISTICA', 'Quísticas'),('SOLIDA', 'Sólidas')))
	horarioizq=models.CharField(max_length=400,verbose_name='HORARIO')
	horarioder=models.CharField(max_length=400,verbose_name='HORARIO')
	descripcionizq=models.CharField(max_length=500,verbose_name='DESCRIPCION')
	descripcionder=models.CharField(max_length=500,verbose_name='DESCRIPCION')
	observaciones=models.CharField(max_length=500,verbose_name='OBSERBACIONES')
	presuncion=models.CharField(max_length=800,verbose_name='PRESIÓN DIAGNÓSTICA')
	fech_analisismamas=models.DateTimeField(auto_now_add=True,verbose_name='FECHA DE ADMISION')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='FECHA DE ACTUALIZACION')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)
	def get_absolute_url(self):
		return reverse('registros:ecografia')

class analisisAbdominal(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	movilidad_higado=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('ANORMAL', 'Anormal')))
	bordes_higado=models.CharField(max_length=20,choices=(('REGULAR', 'Regulares'),('IRREGULAR', 'Irregulares')))
	dimension_higado=models.CharField(max_length=20,choices=(('NORMALES', 'Normales'),('OTROS', 'Otros')))
	parenquima_higado=models.CharField(max_length=20,choices=(('HOMOGENEO', 'Homogéneo'),('HETEROGENEO', 'Heterogéneo')))
	ecogenicidad_higado=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('DISMINUIDA', 'Disminuida'),('AUMENTADA', 'Aumentada')))
	imgExpansivas_higado=models.CharField(max_length=2,choices=(('NO', 'No'),('SI', 'Si')))
	dilatacionVilar_higado=models.CharField(max_length=2,choices=(('NO', 'No'),('SI', 'Si')))
	coledoco_higado=models.CharField(max_length=200,verbose_name='COLEDOCO')
	forma_vesicula=models.CharField(max_length=200,verbose_name='FORMA')
	paredes_vesicula=models.CharField(max_length=20,choices=(('REGULAR', 'Regulares'),('IRREGULAR', 'Irregulares')))
	contenidoanecoico_vesicula=models.CharField(max_length=2,choices=(('NO', 'No'),('SI', 'Si')))
	calculointerno_vesicula=models.CharField(max_length=200,verbose_name='CALCULOS INTERNOS')
	diametrotransverso_vesicula=models.CharField(max_length=200,verbose_name='DIAMETRO TRANSVERSOS')
	ecogenicidad_pancreas=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('ANORMAL', 'Anormal')))
	medidas_pancreas=models.CharField(max_length=200,verbose_name='MEDIDAS')
	ecogenidad_bazo=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('ANORMAL', 'Anormal')))
	medidas_bazo=models.CharField(max_length=200,verbose_name='MEDIDAS')
	aorta=models.CharField(max_length=200,verbose_name='CALIBRES')
	liquido_abdominal=models.CharField(max_length=2,choices=(('NO', 'No'),('SI', 'Si')))
	observaciones=models.CharField(max_length=200,verbose_name='OBSERBACIONES')
	presuncion_diagnostico=models.CharField(max_length=500,verbose_name='PRESUNCION_DIAGNOSTICA')
	fech_analisisabdomen=models.DateTimeField(auto_now_add=True,verbose_name='FECHA DE ADMISION')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='FECHA DE ACTUALIZACION')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)

	def get_absolute_url(self):
		return reverse('registros:ecografia')

	def __str__(self):
		return str(self.paciente)+' '+str(self.fech_analisisabdomen)

class analisisObstetrico(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	numero=models.PositiveSmallIntegerField(default=1)
	situacion=models.CharField(max_length=20,choices=(('LONGITUDINAL', 'Longitudinal'),('TRANSVERSAL', 'TRANSVERSAL'),('OBLICUA', 'Oblicua')))
	presentacion=models.CharField(max_length=20,choices=(('CEFALICO', 'Cefalico'),('PODALICO', 'Podalico'),('OTROS', 'Otros')))
	dorso=models.CharField(max_length=20,choices=(('IZQUIERDA', 'Izquierda'),('DERECHA', 'Derecha'),('ANTERIOR', 'Anterior'),('POSTERIOR', 'Posterior')))
	dbp=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='DBP(mm)')
	lf=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='LF(mm)')
	sg=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='SG(mm)')
	lcn=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='LCN(mm)')
	columnaVertebral=models.CharField(max_length=20,choices=(('PRESENTE', 'Presente'),('CAMARA GASTRICA', 'Camara Gástrica')))
	riñon=models.CharField(max_length=20,choices=(('PRESENTE', 'Presente'),('VEJIGA', 'Vejiga')))
	actividadCardiaca=models.CharField(max_length=20,choices=(('PRESENTE', 'Presente'),('OTRO', 'Otro')))
	movimientoFetal=models.CharField(max_length=20,choices=(('PRESENTE', 'Presente'),('OTRO', 'Otro')))
	descrionFetal=models.CharField(max_length=300,verbose_name='DESCRIPCION')
	localizacionPlacenta=models.CharField(max_length=20,choices=(('FUNDICA', 'Fúndica'),('ANTERIOR', 'Anterior'),('POSTERIOR', 'Posterior'),('OTROS', 'Otras Posiciones')))
	grado=models.CharField(max_length=20,choices=(('0', '0'),('I', 'I'),('II', 'II'),('III', 'III')))
	espesorplacenta=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Espesor placentario(mm)')
	descrionplacenta=models.CharField(max_length=300,verbose_name='DESCRIPCION')
	volumen=models.CharField(max_length=20,choices=(('NORMAL', 'Fúndica'),('OLIGOHIDRAMNIOS', 'Oligohidramnios'),('POLIHIDRAMNIOS', 'Polihidramnios')))
	descrionamniotica=models.CharField(max_length=300,verbose_name='DESCRIPCION')
	circulardecordon=models.CharField(max_length=2,choices=(('NO', 'No'),('SI', 'Si')))
	observaciones=models.CharField(max_length=300,verbose_name='OBSERVACIONES')
	presuncionDiagnostico=models.CharField(max_length=500,verbose_name='PRESUNCION_DIAGNOSTICA:El estudio Ultrasonografico es compatible con:')
	fech_analisisobstetrico=models.DateTimeField(auto_now_add=True,verbose_name='FECHA ANALISIS OBSTETRICO')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='FECHA DE ACTUALIZACION')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)
	
	def get_absolute_url(self):
		return reverse('registros:ecografia')

	def __str__(self):
		return str(self.paciente)+' '+str(self.fech_analisisobstetrico)

class ecografiaRenal(models.Model): 
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	motivoExamen=models.CharField(max_length=500,verbose_name='MOTIVO DEL EXAMEN')
	movilidad_riñonder=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('ANORMAL', 'Anormal')))
	movilidad_riñonizq=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('ANORMAL', 'Anormal')))
	ecogenicidad_riñonder=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('AUMENTADA', 'Aumentada'),('DISMINUIDA', 'Disminuida')))
	ecogenicidad_riñonizq=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('AUMENTADA', 'Aumentada'),('DISMINUIDA', 'Disminuida')))
	medidalongitud_riñonder=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Longitudinal(mm)')
	medidalongitud_riñonizq=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Longitudinal(mm)')
	medidaparenquima_riñonder=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Parenquima(mm)')
	medidaparenquima_riñonizq=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Parenquima(mm)')
	imgExpansivas_solidasder=models.CharField(max_length=2,choices=(('NO', 'No'),('SI', 'Si')))
	imgExpansivas_solidasizq=models.CharField(max_length=2,choices=(('NO', 'No'),('SI', 'Si')))
	imgExpansivas_quisticasder=models.CharField(max_length=2,choices=(('NO', 'No'),('SI', 'Si')))
	imgExpansivas_quisticasizq=models.CharField(max_length=2,choices=(('NO', 'No'),('SI', 'Si')))
	hidronefrosisder=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Hidronefrosis(mm)')
	hidronefrosisizq=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Hidronefrosis(mm)')
	microlitiasisder=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Microlitiasis(mm)')
	microlitiasisizq=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Microlitiasis(mm)')
	calculo_der=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Calculos(mm)')
	calculo_izq=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Calculos(mm)')
	descripcionder=models.CharField(max_length=500,verbose_name='DESCRIPCION')
	descripciondizq=models.CharField(max_length=500,verbose_name='DESCRIPCION')
	replecion=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('MINIMO', 'Minimo'),('EXCESIVA', 'Excesova')))
	paredes=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('DELGADA', 'Delgada'),('ENGROSADA', 'Engrosada')))
	contenidoAnecoico=models.CharField(max_length=200,verbose_name='Conteniso anecoico')
	imgExpansivasvegiga=models.CharField(max_length=200,verbose_name='Imagenes expansivas')
	calculointerior=models.CharField(max_length=200,verbose_name='Calculos en su interior')
	volpremicional=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='volpremicional(cc)')
	volpostmiccional=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='volpostmiccional(cc)')
	retencion=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='retencion(cc)')
	descripcionveg=models.CharField(max_length=500,verbose_name='DESCRIPCION')
	observaciones=models.CharField(max_length=200,verbose_name='OBSERBACIONES')
	presuncionDiagnostico=models.CharField(max_length=500,verbose_name='PRESUNCION_DIAGNOSTICA')
	fech_informe=models.DateTimeField(auto_now_add=True,verbose_name='FECHA INFORME ECOGRAFICO RENAL')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='FECHA DE ACTUALIZACION')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)

	def get_absolute_url(self):
		return reverse('registros:ecografia')

	def __str__(self):
		return str(self.paciente)+' '+str(self.fech_informe)


class ecografiaginecologico(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	motivoExamen=models.CharField(max_length=500,verbose_name='MOTIVO DEL EXAMEN')
	posicionUtero=models.CharField(max_length=20,choices=(('ANTEVERSO', 'Anteverso'),('CENTRAL', 'Central'),('RETROVRSO', 'Retroverso')))
	contornoUtero=models.CharField(max_length=100,verbose_name='CONTORNO')
	ecoestructura=models.CharField(max_length=100,verbose_name='ESTRUCTURA')
	medidas=models.CharField(max_length=100,verbose_name='MEDIDAS')
	endometrio=models.CharField(max_length=20,choices=(('MENSTRUAL', 'Menstrual'),('PROLIF', 'Prolif.'),('PERIOF', 'Periof.'),('SECRET', 'Secret')))
	descripcion=models.CharField(max_length=500,verbose_name='DESCRIPCION')
	anexodermedidas=models.CharField(max_length=200,verbose_name='DESCRIPCION')
	anexodermasas=models.CharField(max_length=20,choices=(('NO', 'No'),('QUISTE', 'Quiste.'),('SOLIDAS', 'Solidas.')))
	anexoderdescripcion=models.CharField(max_length=300,verbose_name='DESCRIPCION')
	anexoizqmedidas=models.CharField(max_length=200,verbose_name='DESCRIPCION')
	anexoizqmasas=models.CharField(max_length=20,choices=(('NO', 'No'),('QUISTE', 'Quiste.'),('SOLIDAS', 'Solidas.')))
	anexoizqdescripcion=models.CharField(max_length=300,verbose_name='DESCRIPCION')
	liquidolibre=models.CharField(max_length=20,choices=(('NO', 'No'),('ESCASO', 'Escaso.'),('MODERADO', 'Moderado.'),('ABUNDANTE', 'Abundante.')))
	observacion=models.CharField(max_length=500,verbose_name='OBSERVACION')
	presuncionDiagnostico=models.CharField(max_length=500,verbose_name='PRESUNCION_DIAGNOSTICA')
	fech_informe=models.DateTimeField(auto_now_add=True,verbose_name='FECHA INFORME ECOGRAFICO GINECOLOGICO')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='FECHA DE ACTUALIZACION')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)

	def get_absolute_url(self):
		return reverse('registros:ecografia')

class ecografiatesticular(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	motivoExamen=models.CharField(max_length=500,verbose_name='MOTIVO DEL EXAMEN')
	testiculoder=models.CharField(max_length=300,verbose_name='DERECHO')
	epididimoder=models.CharField(max_length=300,verbose_name='EPIDIDIMODER')
	liqescrotalder=models.CharField(max_length=300,verbose_name='LIQUIDO INTRA ESCROTAL')
	testiculoizq=models.CharField(max_length=300,verbose_name='IZQUIERDO')
	epididimoizq=models.CharField(max_length=300,verbose_name='EPIDIDIMODER')
	liqescrotalizq=models.CharField(max_length=300,verbose_name='LIQUIDO INTRA ESCROTAL')
	observacion=models.CharField(max_length=500,verbose_name='OBSERVACION')
	presuncionDiagnostico=models.CharField(max_length=500,verbose_name='PRESUNCION_DIAGNOSTICA')
	fech_informe=models.DateTimeField(auto_now_add=True,verbose_name='FECHA INFORME ECOGRAFICO TESTICULAR')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='FECHA DE ACTUALIZACION')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)

	def get_absolute_url(self):
		return reverse('registros:ecografia')

	def __str__(self):
		return str(self.paciente)+' '+str(self.fech_informe)


class ecografiaprostata(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	repelecion=models.CharField(max_length=20,choices=(('BUENA', 'Buena'),('VACUA', 'Vacua'),('POCA', 'Poca')))
	paredes=models.CharField(max_length=20,choices=(('REGULARES', 'Regulares'),('IRREGULARES', 'Irregulares'),('DELGADA', 'Delgada'),('ENGROSADA', 'Engrosada')))
	contenidoanecoico=models.CharField(max_length=50,verbose_name='Contenido Anecoico')
	imgExpansivas=models.CharField(max_length=50,verbose_name='Imagenes expansivas')
	calculointerior=models.CharField(max_length=50,verbose_name='Cálculo en su interior')
	volpremiccional=models.CharField(max_length=200,verbose_name='Vol. Pre-miccional')
	descripcion=models.CharField(max_length=200,verbose_name='Descripcion/Otros')
	bordes=models.CharField(max_length=100,verbose_name='Bordes')
	dimensiones=models.CharField(max_length=400,verbose_name='Dimensiones')
	volumen=models.CharField(max_length=100,verbose_name='Volumen')
	ecoestructura=models.CharField(max_length=100,verbose_name='Bordes')
	observacion=models.CharField(max_length=500,verbose_name='OBSERVACION')
	presuncionDiagnostico=models.CharField(max_length=500,verbose_name='PRESUNCION_DIAGNOSTICA')
	fech_informe=models.DateTimeField(auto_now_add=True,verbose_name='FECHA INFORME ECOGRAFICO PROSTATA')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='FECHA DE ACTUALIZACION')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)

	def get_absolute_url(self):
		return reverse('registros:ecografia')

	def __str__(self):
		return str(self.paciente)+' '+str(self.fech_informe)


class desintometria(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	encabezado = models.CharField(max_length=50,verbose_name='Encabezado')
	observaciones = models.CharField(max_length=10000,verbose_name='Observaciones')
	fech_informe=models.DateTimeField(auto_now_add=True,verbose_name='')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)

class rayosx(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	encabezado = models.CharField(max_length=50,verbose_name='Encabezado')
	observaciones = models.CharField(max_length=10000,verbose_name='Observaciones')
	fech_informe=models.DateTimeField(auto_now_add=True,verbose_name='')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)

class terapias(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	encabezado = models.CharField(max_length=50,verbose_name='Encabezado')
	observaciones = models.CharField(max_length=10000,verbose_name='Observaciones')
	fech_informe=models.DateTimeField(auto_now_add=True,verbose_name='')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)

class ekg(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	encabezado = models.CharField(max_length=50,verbose_name='Encabezado')
	observaciones = models.CharField(max_length=10000,verbose_name='Observaciones')
	fech_informe=models.DateTimeField(auto_now_add=True,verbose_name='')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)

class lab_analisisclinico(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	hematies = models.CharField(max_length=50,verbose_name='Hematies',blank=True,null=True)
	leucocitos = models.CharField(max_length=50,verbose_name='leucocitos',blank=True,null=True)
	hematocrito = models.CharField(max_length=50,verbose_name='hematocrito',blank=True,null=True)
	hemoglobina = models.CharField(max_length=50,verbose_name='hemoglobina',blank=True,null=True)
	hdeshiling = models.CharField(max_length=50,verbose_name='H. de Shiling',blank=True,null=True)
	eritrosidimentacion = models.CharField(max_length=50,verbose_name='eritrosidimentacion',blank=True,null=True)
	plaquetas = models.CharField(max_length=50,verbose_name='plaquetas',blank=True,null=True)
	reticulocitos = models.CharField(max_length=50,verbose_name='reticulocitos',blank=True,null=True)
	tdesangria = models.CharField(max_length=50,verbose_name='tdesangria',blank=True,null=True)
	tdecoagulacion = models.CharField(max_length=50,verbose_name='tdecoagulacion',blank=True,null=True)
	tdeprotombina = models.CharField(max_length=50,verbose_name='tdeprotombina',blank=True,null=True)
	tdetromboplast = models.CharField(max_length=50,verbose_name='tdetromboplast',blank=True,null=True)
	fibrinogeno = models.CharField(max_length=50,verbose_name='fibrinogeno',blank=True,null=True)
	gruposanguineo = models.CharField(max_length=50,verbose_name='gruposanguineo',blank=True,null=True)
	factorrh = models.CharField(max_length=50,verbose_name='factorrh',blank=True,null=True)
	rdewidal = models.CharField(max_length=50,verbose_name='rdewidal',blank=True,null=True)
	plasmodium = models.CharField(max_length=50,verbose_name='plasmodium',blank=True,null=True)
	vdrlcualit = models.CharField(max_length=50,verbose_name='vdrlcualit',blank=True,null=True)
	vdrlcuantit = models.CharField(max_length=50,verbose_name='vdrlcuantit',blank=True,null=True)
	testdecombs = models.CharField(max_length=50,verbose_name='testdecombs',blank=True,null=True)
	rcreactiva = models.CharField(max_length=50,verbose_name='rcreactiva',blank=True,null=True)
	ratest = models.CharField(max_length=50,verbose_name='ratest',blank=True,null=True)
	asto = models.CharField(max_length=50,verbose_name='asto',blank=True,null=True)
	factorrematoideo = models.CharField(max_length=50,verbose_name='factorrematoideo',blank=True,null=True)
	acurico = models.CharField(max_length=50,verbose_name='acurico',blank=True,null=True)
	urea = models.CharField(max_length=50,verbose_name='urea',blank=True,null=True)
	creatinina = models.CharField(max_length=50,verbose_name='creatinina',blank=True,null=True)
	glucosa = models.CharField(max_length=50,verbose_name='glucosa',blank=True,null=True)
	glucosapostprandial = models.CharField(max_length=50,verbose_name='glucosapostprandial',blank=True,null=True)
	hemoglobinaglicosilada = models.CharField(max_length=50,verbose_name='hemoglobinaglicosilada',blank=True,null=True)
	testtoleranciaglucosa = models.CharField(max_length=50,verbose_name='testtoleranciaglucosa',blank=True,null=True)
	colesterol = models.CharField(max_length=50,verbose_name='colesterol',blank=True,null=True)
	hdlcoleseterol = models.CharField(max_length=50,verbose_name='hdlcoleseterol',blank=True,null=True)
	ldlcolesterol = models.CharField(max_length=50,verbose_name='ldlcolesterol',blank=True,null=True)
	trigliceridos = models.CharField(max_length=50,verbose_name='trigliceridos',blank=True,null=True)
	lipidostotales = models.CharField(max_length=50,verbose_name='lipidostotales',blank=True,null=True)
	sodio = models.CharField(max_length=50,verbose_name='sodio',blank=True,null=True)
	cloro = models.CharField(max_length=50,verbose_name='cloro',blank=True,null=True)
	potasio = models.CharField(max_length=50,verbose_name='potasio',blank=True,null=True)
	calcio = models.CharField(max_length=50,verbose_name='calcio',blank=True,null=True)
	magnesio = models.CharField(max_length=50,verbose_name='magnesio',blank=True,null=True)
	feserico = models.CharField(max_length=50,verbose_name='feserico',blank=True,null=True)
	bilirrubinatotal = models.CharField(max_length=50,verbose_name='bilirrubinatotal',blank=True,null=True)
	bdirecta = models.CharField(max_length=50,verbose_name='bdirecta',blank=True,null=True)
	bindirecta = models.CharField(max_length=50,verbose_name='bindirecta',blank=True,null=True)
	indicterico = models.CharField(max_length=50,verbose_name='indicterico',blank=True,null=True)
	proteinastotales = models.CharField(max_length=50,verbose_name='proteinastotales',blank=True,null=True)
	albumina = models.CharField(max_length=50,verbose_name='albumina',blank=True,null=True)
	globulina = models.CharField(max_length=50,verbose_name='globulina',blank=True,null=True)
	got = models.CharField(max_length=50,verbose_name='got',blank=True,null=True)
	gpt = models.CharField(max_length=50,verbose_name='gpt',blank=True,null=True)
	colinesterasa = models.CharField(max_length=50,verbose_name='colinesterasa',blank=True,null=True)
	dlh = models.CharField(max_length=50,verbose_name='dlh',blank=True,null=True)
	fofatalcalina = models.CharField(max_length=50,verbose_name='fofatalcalina',blank=True,null=True)
	fofatacidaprost = models.CharField(max_length=50,verbose_name='fofatacidaprost',blank=True,null=True)
	ggtp = models.CharField(max_length=50,verbose_name='ggtp',blank=True,null=True)
	cpk = models.CharField(max_length=50,verbose_name='cpk',blank=True,null=True)
	cpkmb = models.CharField(max_length=50,verbose_name='cpkmb',blank=True,null=True)
	amilasaorina = models.CharField(max_length=50,verbose_name='amilasaorina',blank=True,null=True)
	amilasaserica = models.CharField(max_length=50,verbose_name='amilasaserica',blank=True,null=True)
	lipasaserica = models.CharField(max_length=50,verbose_name='lipasaserica',blank=True,null=True)
	toxoplasmalgg = models.CharField(max_length=50,verbose_name='toxoplasmalgg',blank=True,null=True)
	toxoplasmalgm = models.CharField(max_length=50,verbose_name='toxoplasmalgm',blank=True,null=True)
	hepatitisalgg = models.CharField(max_length=50,verbose_name='hepatitisalgg',blank=True,null=True)
	hepatitisalgm = models.CharField(max_length=50,verbose_name='hepatitisalgm',blank=True,null=True)
	hepatitisbhbsag = models.CharField(max_length=50,verbose_name='hepatitisbhbsag',blank=True,null=True)
	hepatitisc = models.CharField(max_length=50,verbose_name='hepatitisc',blank=True,null=True)
	vurusherpes1lgg = models.CharField(max_length=50,verbose_name='vurusherpes1lgg',blank=True,null=True)
	vurusherpes1y2lgm = models.CharField(max_length=50,verbose_name='vurusherpes1y2lgm',blank=True,null=True)
	vurusherpes2lgg = models.CharField(max_length=50,verbose_name='vurusherpes2lgg',blank=True,null=True)
	dengue = models.CharField(max_length=50,verbose_name='dengue',blank=True,null=True)
	vih = models.CharField(max_length=50,verbose_name='vih',blank=True,null=True)
	ige = models.CharField(max_length=50,verbose_name='ige',blank=True,null=True)
	alfafetoproteina = models.CharField(max_length=50,verbose_name='alfafetoproteina',blank=True,null=True)
	agcarcinoembrionario = models.CharField(max_length=50,verbose_name='agcarcinoembrionario',blank=True,null=True)
	agprostespcif = models.CharField(max_length=50,verbose_name='agprostespcif',blank=True,null=True)
	agprostespecificolibre = models.CharField(max_length=50,verbose_name='agprostespecificolibre',blank=True,null=True)
	ca153mama = models.CharField(max_length=50,verbose_name='ca153mama',blank=True,null=True)
	ca125ovario = models.CharField(max_length=50,verbose_name='ca125ovario',blank=True,null=True)
	ca724gastrico = models.CharField(max_length=50,verbose_name='ca724gastrico',blank=True,null=True)
	ca199pancreas = models.CharField(max_length=50,verbose_name='ca199pancreas',blank=True,null=True)
	t3 = models.CharField(max_length=50,verbose_name='t3',blank=True,null=True)
	t4 = models.CharField(max_length=50,verbose_name='t4',blank=True,null=True)
	tsh = models.CharField(max_length=50,verbose_name='tsh',blank=True,null=True)
	fsh = models.CharField(max_length=50,verbose_name='fsh',blank=True,null=True)
	prolactina = models.CharField(max_length=50,verbose_name='prolactina',blank=True,null=True)
	progesterona = models.CharField(max_length=50,verbose_name='progesterona',blank=True,null=True)
	betaestradiol = models.CharField(max_length=50,verbose_name='betaestradiol',blank=True,null=True)
	testosterona = models.CharField(max_length=50,verbose_name='testosterona',blank=True,null=True)
	hcgsubbetaembarazo = models.CharField(max_length=50,verbose_name='hcgsubbetaembarazo',blank=True,null=True)
	hcgsubbetacuantit = models.CharField(max_length=50,verbose_name='hcgsubbetacuantit',blank=True,null=True)
	fisico = models.CharField(max_length=50,verbose_name='fisico',blank=True,null=True)
	quimico = models.CharField(max_length=50,verbose_name='quimico',blank=True,null=True)
	sedimiento = models.CharField(max_length=50,verbose_name='sedimiento',blank=True,null=True)
	cultivoyambiograma = models.CharField(max_length=50,verbose_name='cultivoyambiograma',blank=True,null=True)
	contajedecolonias = models.CharField(max_length=50,verbose_name='contajedecolonias',blank=True,null=True)
	gravindex = models.CharField(max_length=50,verbose_name='gravindex',blank=True,null=True)
	depuraciondecreatinina = models.CharField(max_length=50,verbose_name='depuraciondecreatinina',blank=True,null=True)
	proteinasenorina = models.CharField(max_length=50,verbose_name='proteinasenorina',blank=True,null=True)
	parasitologico = models.CharField(max_length=50,verbose_name='parasitologico',blank=True,null=True)
	porconcentracion = models.CharField(max_length=50,verbose_name='porconcentracion',blank=True,null=True)
	estuddemocofecal = models.CharField(max_length=50,verbose_name='estuddemocofecal',blank=True,null=True)
	sangreoculta = models.CharField(max_length=50,verbose_name='sangreoculta',blank=True,null=True)
	trinciondegram = models.CharField(max_length=50,verbose_name='trinciondegram',blank=True,null=True)
	cultivoyantibiograma = models.CharField(max_length=50,verbose_name='cultivoyantibiograma',blank=True,null=True)
	rotavirus = models.CharField(max_length=50,verbose_name='rotavirus',blank=True,null=True)
	parasitos = models.CharField(max_length=50,verbose_name='parasitos',blank=True,null=True)
	tinciondegram = models.CharField(max_length=50,verbose_name='tinciondegram',blank=True,null=True)
	zielbdek = models.CharField(max_length=50,verbose_name='zielbdek',blank=True,null=True)
	cultivoyantibiogramastrpa = models.CharField(max_length=50,verbose_name='cultivoyantibiogramastrpa',blank=True,null=True)
	porcentdeesosinofilos = models.CharField(max_length=50,verbose_name='porcentdeesosinofilos',blank=True,null=True)
	enfresco = models.CharField(max_length=50,verbose_name='enfresco',blank=True,null=True)
	cultivoyantibiogramavaginal = models.CharField(max_length=50,verbose_name='cultivoyantibiogramavaginal',blank=True,null=True)
	chiamydia = models.CharField(max_length=50,verbose_name='chiamydia',blank=True,null=True)
	neisseria = models.CharField(max_length=50,verbose_name='neisseria',blank=True,null=True)
	otros = models.CharField(max_length=50,verbose_name='otros',blank=True,null=True)
	fech_informe=models.DateTimeField(auto_now_add=True,verbose_name='')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)